alias: Daniels Thermostat Schedule
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.summer_daniels_thermostat_schedule
      - sensor.winter_daniels_thermostat_schedule
      - script.zone_control_script
  - platform: time_pattern
    minutes: /5
  - platform: template
    value_template: "{{ states('climate.daniel_s') != 'off' }}"
condition:
  - condition: template
    value_template: >-
      {% set condition_state = states(condition) not in ['unavailable',
      'unknown'] and states('climate.daniel_s') != 'off' %}  {% set
      zone_control_trigger = trigger.entity_id == 'script.zone_control_script'
      and trigger.to_state.state == 'off'  %} {% set zone_control_state =
      is_state('script.zone_control_script', 'off') %} {{ (zone_control_state or
      zone_control_trigger) and condition_state }}
action:
  - service: script.master_thermostat_schedule
    data:
      input_boolean: input_boolean.daniels_threshold_control
      input_number: input_number.daniels_scheduled_temperature
      thermostat: climate.daniel_s
      schedule: >-
        {% if states('climate.daniel_s') == 'cool' %}
        sensor.summer_daniels_thermostat_schedule {% elif
        states('climate.daniel_s') == 'heat' %}
        sensor.winter_daniels_thermostat_schedule {% endif %}
mode: single
variables:
  condition: >-
    {% if states('climate.daniel_s') == 'cool' %}
    sensor.summer_daniels_thermostat_schedule  {% elif
    states('climate.daniel_s') == 'heat' %}
    sensor.winter_daniels_thermostat_schedule  {% endif %}
